name: 💬 Feedback oder Fehler melden
description: Allgemeines Feedback, Bugs oder Ideen
title: "[Feedback] <Kurzbeschreibung>"
labels: ["feedback"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Was möchtest du melden?
      options:
        - Bug
        - Feature Request
        - Allgemeines Feedback

  - type: input
    id: title
    attributes:
      label: Kurzbeschreibung
      description: Fasse dein Anliegen in einem Satz zusammen
      placeholder: z. B. "Button funktioniert nicht in Firefox"

  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Beschreibe das Problem oder deine Idee
      placeholder: So ausführlich wie nötig, gern mit Screenshots oder Code

  - type: checkboxes
    id: checks
    attributes:
      label: Ich habe geprüft...
      options:
        - label: ...ob dieses Issue schon existiert
        - label: ...ob ich die neueste Version verwendet habe